### ISSUE TITLE
Where do I download the Psi API from?

### ISSUE THREAD

**Issue by crabdancing** [Snownee/LightingWand#10]
Ideally, the build chain would automatically pull the Psi API, but it doesn't seem to do so. Where do I find the API files to compile against And how do I compile against them? I tried pulling Vazkii/Psi into the repo directory, but that's not working.

**Comment by Snownee** [comment]
```
repositories {
    maven { url = "http://dvs1.progwml6.com/files/maven" }
}
```

**Comment by crabdancing** [comment]
That didn't work. :( It terminates with the same "cannot find symbol" error. Gradle is not downloading the API.

**Comment by Snownee** [comment]
https://github.com/Kamefrede/reskillablepsicompat/tree/master/libs
this should work

**Comment by crabdancing** [comment]
That worked! Thanks :D
