### ISSUE TITLE
[1.12.2] Question: How do I make the wand use energy?

### ISSUE THREAD

**Issue by Dimentive** [Snownee/LightingWand#11]
Do I just turn off the repair recipe in the config, or is there another way?

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847 (latest for 1.12.2)
* **Lighting Wand:** 1.0.4 (latest for 1.12.2)

**Comment by Snownee** [comment]
I think it is enabled by default, so all you need to do is put the wand in a Forge energy charger

**Comment by Dimentive** [comment]
@Snownee Well, I tried putting the lighting wand in an Ender IO wired charger, but it wouldn’t accept it.

**Comment by Snownee** [comment]
Try other mods?

**Comment by Dimentive** [comment]
I was able to recharge it with RF in Actually Addition’s Energizer, but for some reason, it only repaired one or two durability points at a time.

**Comment by crabdancing** [comment]
I too can't recharge it in EnderIO Wired Charger. :(

EnderIO is the core tech mod for my modpack, so I'm not sure what to do.

**Comment by Dimentive** [comment]
Closing this as I’ve created two new issues for the two bugs that I discovered:
* #13 – Cannot use Ender IO’s wired charger to repair the lighting wand
* #14 – Actually Additions’ energizer repairs the lighting wand by one or two durability points at a time, rather than repairing it all at once
