### ISSUE TITLE
[1.12.2] Cannot use Ender IO’s wired charger to recharge the lighting wand

### ISSUE THREAD

**Issue by Dimentive** [Snownee/LightingWand#13]
The lighting wand is unable to be charged in [Ender IO’s](https://www.curseforge.com/minecraft/mc-mods/ender-io) wired charger and simple wired charger.

I will soon test to see if the same goes for Ender IO’s wireless charger, [Actually Additions’](https://www.curseforge.com/minecraft/mc-mods/actually-additions) batteries, and other charging methods.

I did test with Actually Additions’ energizer, and that did successfully charge the lighting wand.

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847 (latest for 1.12.2)
* **Lighting Wand:** 1.0.4 (latest for 1.12.2)
* **Ender IO:** 5.1.52 (latest)
* **[EnderCore](https://www.curseforge.com/minecraft/mc-mods/endercore):** 0.5.73 (latest)

**Comment by Snownee** [comment]
I think the enhanced wired charger should work?

**Comment by Snownee** [comment]
SleepyTrousers/EnderIO#5306
