### ISSUE TITLE
[1.12.2] Actually Additions’ battery charges the lighting wand one or two durability points at a time

### ISSUE THREAD

**Issue by Dimentive** [Snownee/LightingWand#14]
When I charge the lighting wand in [Actually Additions’](https://www.curseforge.com/minecraft/mc-mods/actually-additions) energizer, a block that charges items that use RF, by putting it into the input slot as usual, it goes into the output slot as expected, but it’s not fully charged, only being repaired around one or two durability points. I have to repeat the process until it’s completely charged.

Maybe it has something to do with the lighting wand using durability points instead of energy despite being repairable in machines that repair items that use energy. I’m not sure how that works.

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847 (latest for 1.12.2)
* **Lighting Wand:** 1.0.4 (latest for 1.12.2)
* **Actually Additions:* r151

**Comment by Snownee** [comment]
That is how it works

**Comment by Dimentive** [comment]
All right. Why, though? It’s quite tedious.

**Comment by Snownee** [comment]
1. It is easier to implement
2. It is more balanced

**Comment by Dimentive** [comment]
Making something more tedious for the sake of being more tedious is not more balanced. It doesn’t require more resources; it just takes more time for no reason. That’s not what balance is.
