### ISSUE TITLE
[1.15.2]光源不显示粒子

### ISSUE THREAD

**Issue by EnterFor** [Snownee/LightingWand#15]
* Minecraft Version:1.15.2
 * Mod Version:1.4.2
 * Forge Version:31.1.35
![image](https://user-images.githubusercontent.com/10114685/78336364-d28fd180-75c1-11ea-9702-82ff9e7604a6.png)
如图，只有对准时显示方块边框，如果放置的过多，很难找出位置。。
这是Forge自身的问题吗？

**Comment by Snownee** [comment]
光源应该显示粒子，不显示可能是因为你把粒子效果关掉了。

**Comment by EnterFor** [comment]
.....我是真的憨，抱歉
