### ISSUE TITLE
Not working in 1.15.2 - no action on right click with wand

### ISSUE THREAD

**Issue by Quandru** [Snownee/LightingWand#16]
Right clicking with the wand doesn't appear to be doing anything.

Running:
- Minecraft 1.15.2
- Forge 31.1.44
- LightingWand 1.4.2 for 1.15.2

No other mods installed.

Wand shows up in creative mode block search fine, but in creative or survival right clicking does nothing.

Let me know if you need any extra info.

**Comment by Quandru** [comment]
Video of this in progress here
https://youtu.be/r0EEtIVVrDM

**Comment by Snownee** [comment]
I can't reproduce

**Comment by Quandru** [comment]
I'm not sure how to move forward then; it's a brand new Java install, above version, literally the only mods running are Forge and LightingWand and the wand simply doesn't do anything.

Is there any logging that your mod does which I can send you to diagnose or what is the next step in terms of investigating?

**Comment by Quandru** [comment]
Or are there any other undocumented prerequisites or anything?

**Comment by Snownee** [comment]
Are you playing in a local world?

**Comment by Quandru** [comment]
No, it's a Java based dedicated server I run.

**Comment by Snownee** [comment]
Still cannot reproduce with forge server

**Comment by Quandru** [comment]
OK, in the absence of any feedback on logging, etc. that might help you diagnose further, I don't know what else to suggest. I have removed it and installed an alternate which is working fine. Thanks.
