### ISSUE TITLE
[1.14.3] noSuchFieldException: maxDamage

### ISSUE THREAD

**Issue by ProsperCraft** [Snownee/LightingWand#2]
Error on startup-
LightingWand-1.14.3-1.2.0

Relevant section
https://gist.github.com/ProsperCraft/ecc178ccf29ebb16841e7a23dd2201e8

Full log-
https://gist.github.com/ProsperCraft/d69e77dc4363868fbb4c3fe2ed9cb01e

**Comment by Snownee** [comment]
Thanks for reporting! Should be fixed in the next release
