### ISSUE TITLE
New light sources are dim after some time being used in a map

### ISSUE THREAD

**Issue by JillSwift** [Snownee/LightingWand#24]
If bug:

 * Forge Version: 36.1.33
 * Mod Version: 1.8.0
 * Can you reproduce this issue with relevant mods only?: yes (forge and LightingWand only)

Paste your crash report to somewhere like https://paste.ubuntu.com/ , instead of directly here.
No crash

Placing light sources work just fine at first on any new map.
However, after a while (seems random) new light sources seem to have a dim setting, around 4 or so.
Wand is charged.

**Comment by Snownee** [comment]
I can't reproduce

**Comment by JillSwift** [comment]
K.I'll try and pin its li'l butt down and let you know what the cause was/is. Thanks for your time :)

**Comment by Pyeroh** [comment]
I encountered the same problem, and I fixed it by repairing the wand, or using another one. I still don't know what happened, but at least it's working again.

**Comment by Snownee** [comment]
Could you guys provide a mod list here? You can get the list from log or force crash

**Comment by Pyeroh** [comment]
For me, it's the same as Create 101 S2 v2.2.3 without modifications

**Comment by Snownee** [comment]
@Pyeroh I think maybe you can try right clicking light block with wand?

**Comment by Pyeroh** [comment]
I tried that, when "it was happening", and it just placed another light block next to it

**Comment by Pyeroh** [comment]
Mea culpa, I guess I didn't look as I should have : when I right click an already placed light source with the wand, it dims it, and I can't get to "undim" that light source, nor the wand can place full light light sources. Still, I can fix that behaviour by repairing the wand.

**Comment by Snownee** [comment]
@Pyeroh When the light value is 1, right clicking the block will return to light 15.

I will add a notification in the next update

**Comment by Zarepheth** [comment]
I stopped by here for the same problem. I didn't realize that I could adjust the light intensity by right-clicking a placed light with the wand. So after some time playing, I'd accidentally set the light value from 15 to 1.  From that point forward, only a new wand would "work". 

Once I realized I could change the light levels, I was able to reset my old wands to 15.
