### ISSUE TITLE
[1.16.5] Wand is repaired by the thermal expansion Flux capacitor

### ISSUE THREAD

**Issue by ProsperCraft** [Snownee/LightingWand#26]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

LightingWand-1.16.4-1.8.1

### Modloader version

forge-1.16.5-36.2.22

### Modpack info

https://www.curseforge.com/minecraft/modpacks/towncraft

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

When the Thermal Flux capacitor is set to active and set to equipment mode, the wand takes a charge of rf from the cap to repair it.  I don't think this is intended behavior, and could lead to a lot of light spam on the server.

**Comment by Snownee** [comment]
This is intented. And I think it can be disabled in config

**Comment by ProsperCraft** [comment]
yes, sure enough, thank you.
