### ISSUE TITLE
Recipe Type not registered

### ISSUE THREAD

**Issue by Laifsyn** [Snownee/LightingWand#27]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.0.0

### Modloader version

Fabric 0.13.3 (I don't remember the api version right now)

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I can't get `recipetype:lightningwand:repair` for CraftTweaker when dumping recipes.  There has been a similar if not the same issue with TechReborn where it was said that their recipe types weren't registered correctly.
[Github Issues Link of the submit](https://github.com/TechReborn/TechReborn/issues/2842)

**Comment by Snownee** [comment]
it's not a recipe type. it is a recipe serializer. its type is minecraft:crafting
