### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by TookUrSweetRoll** [Snownee/LightingWand#3]
Using Forge 27.0.25

![LW](https://user-images.githubusercontent.com/29466666/60768556-46cd3100-a093-11e9-91d8-7e5a9b44b25c.png)

**Comment by Snownee** [comment]
Could you provide the crash report?

**Comment by TookUrSweetRoll** [comment]
It didn't crash, just didn't load. No report was generated.

**Comment by ProsperCraft** [comment]
Just have to know where to look in the log ;)

https://gist.github.com/ProsperCraft/9faf504dd6cbde24664c2de55f7fe6c2

Version 1.14.3 - LightingWand-1.14.3-1.2.1

Load Adventures of Halk version .25 to see the crash live in a pack - 
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by ProsperCraft** [comment]
https://gyazo.com/0643372d12e84742fa56840d51d7b62a

**Comment by Snownee** [comment]
Thank you. I have archived the files

**Comment by Snownee** [comment]
Should have fixed :dizzy_face: Thanks for reporting!
