### ISSUE TITLE
改下gradle.properties

### ISSUE THREAD

**Issue by NativeStar** [Snownee/LightingWand#34]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

1.0.0

### Modloader version

36.2.9

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

希望把"gradle.properties"中jvm参数里的代理设置删掉
折腾了半个多小时才知道为什么编译一直报连不上代理
我的是"1.20.1-forge"分支
(不方便的话也无所谓了 应该很少有人会试着改mod玩)

**Comment by Snownee** [comment]
可是真的不方便
