### ISSUE TITLE
Feature request: Able to place blocks on top of light source + config option

### ISSUE THREAD

**Issue by totrider** [Snownee/LightingWand#35]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

8.0.0

### Modloader version

47.2.19

### Modpack info

https://modrinth.com/modpack/dragon-claw-persistent

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I remember Silent Gear allowing you to make phantom lights, similar to this mod, but you were able to place any block on top of the lights to replace it. This feature is really useful for building, as the lighting wand can provide easy temporary lighting while building.

Unfortunately, it currently gets in the way when building, since you can place anything on top of the light sources, and you need the wand in hand in order to remove them in the first place. It also gets in the way for any other players that come across these lights, as they would need a wand themselves in order to remove them, think mining and spelunking.

Otherwise, this mod does exactly what I was hoping for.

I guess you could also add a config toggle for this feature, but I personally don't see why you would ever need the lights to be intangible without the wand, like they are now.

**Comment by Snownee** [comment]
it's just a bug that causes light block not replaceable anymore
