### ISSUE TITLE
No data fixer registered for entity lightingwand.light

### ISSUE THREAD

**Issue by bloodconfetti** [Snownee/LightingWand#6]
[latest.log](https://github.com/Snownee/LightingWand/files/3493379/latest.log)
Unsure if this is an actual issue or not, but in my latest log it showed a warning for the above, so I wanted to let you know just in case.

**Comment by Snownee** [comment]
I do not think there is someone who wants to migrate their modded world from 1.12 to 1.14.

If anyone needs this feature just let me know and I will fix this.
