### ISSUE TITLE
Common Errors during common setup phase

### ISSUE THREAD

**Issue by lizzyisgay** [Snownee/LightingWand#7]
* Minecraft Version: 1.14.4
 * Mod Version: 1.14

![error](https://user-images.githubusercontent.com/55068554/64497159-bf11c780-d279-11e9-8f6b-edabbf05fef2.png)

**Comment by Wissi** [comment]
Perhaps the same issue.
Full latest.log [here](https://gist.github.com/Wissi/0f5c4380bb6e97888c1050a552a3a834).

Will not load Minecraft at all.
Waiting for your update so we can include in our modpack.
Thanks.
![2019-09-13_22 54 08](https://user-images.githubusercontent.com/23312242/64903150-5a8ba980-d679-11e9-9ca4-fc969349610a.png)
