### ISSUE TITLE
There is no gradlew and I'm not sure how else to compile on Arch Linux

### ISSUE THREAD

**Issue by crabdancing** [Snownee/LightingWand#8]
Pulled straight from git repo as of SHA1 e8036a5b07cf32ea373ca036826513aa69206554. I am getting problems compiling with my gradle version (6.0.1). See the `--debug` output [here](https://gist.githubusercontent.com/alxpettit/4283dc9d9af09069688f185f42ba5043/raw/47b997086c657c6995785858edbd77d9bd6d8040/gradle.log).

This is common when compiling mods with a newer gradle version in my experience. Using the Gradle Wrapper utility for installing a local gradle instance at the version number expected by the project, works fine as a workaround. But I can't do this because there is no [gradlew](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:adding_wrapper).

**Comment by Snownee** [comment]
Hello. You can download directly from mdk https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.15.1.html

**Comment by Snownee** [comment]
https://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.111/forge-1.14.4-28.1.111-mdk.zip

**Comment by crabdancing** [comment]
@Snowee So you can't add the `gradlew` to the repo? I just thought it was standard to include it. Is there some reason not to?

Edit: The recommended way I've seen is to run `gradle wrapper` to build the wrapper from the known good working environment. Seems like it should be trivial to add.

**Comment by Snownee** [comment]
Because I did not use a wrapper when I develop LightingWand for 1.14

**Comment by crabdancing** [comment]
I don't understand why that should preclude its inclusion in the repository, though. I guess it's just a minimalism thing for you?

**Comment by Snownee** [comment]
I have installed gradle on my another PC before so the only thing I need to do is running `gradle xxx`. When you ask me, I checked my 1.14 branch there is no wrapper script

**Comment by Snownee** [comment]
I will include them in my future repos, thanks for your advice

**Comment by crabdancing** [comment]
Welcome! ^_^
