### ISSUE TITLE
LightingWand versions 1.0.3 & 1.0.4 are both causing crashes on Minecraft 1.12.2

### ISSUE THREAD

**Issue by crabdancing** [Snownee/LightingWand#9]
See crash log [here](https://gist.githubusercontent.com/alxpettit/61debebf9c903a9ebc3b66daaf538963/raw/a1b72a50745e62c90ac7936dc3268087996245ad/crash.log).

Edit: it was actually 1.0.3. But I just tested 1.0.4, and got the same result, so there is unlikely to be a regression between the two version numbers.

**Comment by crabdancing** [comment]
Tried wrapping contents of `snownee.lightingwand.common.BlockLight.hasItem` in a `try ... catch`, and it just breaks somewhere else. Tried removing all other mods, and it still breaks. Tried removing LightingWand, and the world loads fine, but without my awesome light wand. :(

**Comment by crabdancing** [comment]
I have a solution! Do you accept pull requests, @Snownee?

**Comment by crabdancing** [comment]
I don't know if you're planning on maintaining the 1.12.2 version. If you don't want to, I could always fork and maintain it for legacy modpacks. Please let me know!

**Comment by Snownee** [comment]
I will but I am too busy these days. I accept PRs but it will be published few days later

**Comment by crabdancing** [comment]
Okay! How do I submit a PR for 1.12.2?

Edit: wait, it's the master branch? I just poked around in the repo, and noticed the master branch happened to have 1.12.2 in the `gradle.properties`...

Just wanted to check with you first, so I don't make a mistake!

**Comment by Snownee** [comment]
@alxpettit yes

**Comment by crabdancing** [comment]
Yay! Commit merged. :) I'll close this issue now.

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/lighting-wand/files/2858668
